name: Auto Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
    - name: Check for changes
      run: |
        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Auto-commit: $(date)"
          git push
        else
          echo "No changes to commit"
        fi 